### ISSUE TITLE
npm start fails compiling

### ISSUE THREAD

**Issue by MochaSteve256** [avikalpg/skyline#14]
First off, i'm a complete noob in npm stuff and also have no clue about typescript.
When i tried to run the project, i first didn't know how to install the dependencies with `npm install`, maybe put that into the readme.
But the real question i have is this error:
```
PS C:\Users\Adrian\Desktop\Code\!misc\skyline> npm start

> skyline@0.1.0 start
> react-scripts start

Failed to compile.

Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.cache.cacheDirectory: The provided value "C:\\Users\\Adrian\\Desktop\\Code\\!misc\\skyline\\node_modules\\.cache" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
   -> Base directory for the cache (defaults to node_modules/.cache/webpack).
 - configuration.module.rules[1].oneOf[3].include: The provided value "C:\\Users\\Adrian\\Desktop\\Code\\!misc\\skyline\\src" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
 - configuration.output.path: The provided value "C:\\Users\\Adrian\\Desktop\\Code\\!misc\\skyline\\build" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
   -> The output directory as **absolute path** (required).
```

I don't know what all this means, so sorry if it sounds dumb lol
also here's the [`npm install log`](https://gist.github.com/MochaSteve256/ab5aa57a8ec7ad05f14013364ec5f2a6), and my npm version is 10.1.0.
I found this repo bc the official skyline isn't working for me as well, if you know a skyline alternative that works for you and has easy setup for noobs pls tell me.

Thanks!

**Comment by avikalpg** [comment]
Hi @MochaSteve256, the path where you have cloned the repository seems to have an exclamation mark in it. 
I am referring to this address in your error log: `"C:\\Users\\Adrian\\Desktop\\Code\\!misc\\skyline\\src"`

I believe the name `!misc` is causing the problem in NPM. 

Can you please try to follow the same steps in a different folder? Or maybe rename the folder `!misc` to `misc`?

Just to recap, the only commands you need to run are:
```bash
npm install
npm start
```

One more thing that you will have to do is create a `.env.local` file that contains an environment variable named `REACT_APP_GITHUB_TOKEN`.

**Comment by MochaSteve256** [comment]
Thanks, now it works, kinda.
Next issue:
![image](https://github.com/avikalpg/skyline/assets/78016786/09d1b3df-564a-46de-a879-6192f459009c)
...
i just put in my name (@MochaSteve256, completely correct). As far as i can tell, there are jsut some deprecated dependencies (is that an issue?).
Here ist the log:
```

> skyline@0.1.0 start
> react-scripts start

(node:21212) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:21212) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
Compiled successfully!

You can now view skyline in the browser.

  Local:            http://localhost:3000/skyline
  On Your Network:  http://192.168.178.42:3000/skyline

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully
No issues found.
```

**Comment by MochaSteve256** [comment]
Hi @avikalpg,
i have personal access tokens, but where's the .env.local file?
I used windows search to look it up in the cloned folder, but didn't find anything.
do i have to create the file myself?
THanks for the responses and sorry for bothering all the time D:

**Comment by avikalpg** [comment]
Yes, you will have to create it yourself. Since `.env.local` file contains secrets, that is why I have ignored it using the `.gitignore` file.

**Comment by avikalpg** [comment]
[This pull request](https://github.com/avikalpg/skyline/pull/16) resolves this issue by clearly stating the steps to use this repository locally.
